# -*- coding: utf-8 -*-
"""Hotel-Booking Cancellation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eJ9CSLth5qyyll0sv16NWY2o4miEUZAa

Importing Libaraies
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""Importing Dataset"""

data= pd.read_csv('/content/hotel_bookings.csv')

data.head()

data.tail()

"""Analyising and Cleaning the Data"""

data.head(10)

data.tail(10)

data.shape

